feat: allow setting apiserver verbosity
Azure/aks-engine pull request #4563
Opened 2021-07-02 13:47 UTC by mweibel

**Reason for Change**:
I think not all users need verbosity level 4 for the apiserver. This logs all requests sent to it and is really quite verbose.

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [x] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

2021-07-02 21:56 UTC, jadarsie commented
lgtm from a functional POV, however I would like to learn why this particular flag was considered static at some point.

2021-07-05 08:04 UTC, mweibel commented
the previous implementation has been added by @jackfrancis in https://github.com/Azure/aks-engine/commit/d216b9438773b007e6e7dfb152ed120ce994bd76 but doesn't mention any specifics. Maybe it was simply not considered important enough to be able to change? 
Other services let also change the verbosity plus the default stays at level 4, so the change shouldn't break anything in this regard.

2021-07-06 20:16 UTC, jackfrancis commented
Thanks @mweibel, there probably isn't a defensible reason for this being 4, and not configurable, just historical.

2021-07-06 20:16 UTC, jackfrancis commented on pkg/api/const.go
> +	DefaultKubernetesAPIServerVerbosity = "4"
While we're making this improvement, let's go ahead and change the default to 2.

2021-07-06 20:17 UTC, jackfrancis requested changes

2021-07-06 20:17 UTC, jackfrancis commented on pkg/api/defaults-apiserver_test.go
> +		"--v": "2",
And if we change the default to 2, let's update this UT case to override to 4 instead

2021-07-07 06:17 UTC, mweibel commented
Thanks for the review. 
I agree and changed the default from 4 to 2.

2021-07-07 13:01 UTC, Michael-Sinz commented
> Thanks for the review.
> I agree and changed the default from 4 to 2.

Please change the commit note/pull request text to mentions that this change not only adds configurability but also changes the default value.  That is a "breaking" change for any users who are used to the default verbosity that existed.  (Not that there should be much of that but it should be called out)

2021-07-07 13:07 UTC, mweibel commented
@Michael-Sinz adjusted the commit msg and the PR text (added `Notes`). Is this how you'd like to have it formatted?

2021-07-07 13:13 UTC, Michael-Sinz commented
> @Michael-Sinz adjusted the commit msg and the PR text (added `Notes`). Is this how you'd like to have it formatted?

Nice - I have added to the title as that is many times the only thing people read :-(

2021-07-07 13:13 UTC, Michael-Sinz approved these changes
/lgtm

2021-07-08 17:12 UTC, jadarsie approved these changes

2021-08-02 13:37 UTC, mweibel commented
ping?

2021-08-02 16:29 UTC, jackfrancis commented
/azp run pr-e2e

2021-08-03 20:56 UTC, jackfrancis approved these changes
/lgtm

2021-08-03 20:56 UTC, merged