chore: Update Azure CNI to v.1.4.12
Azure/aks-engine pull request #4656
Opened 2021-09-17 21:36 UTC by marosset

Signed-off-by: Mark Rossetti <marosset@microsoft.com>

**Reason for Change**:

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

2021-09-17 21:40 UTC, jackfrancis submitted a review, later dismissed
/lgtm

2021-09-20 20:44 UTC, jsturtevant requested changes

2021-09-20 20:44 UTC, jsturtevant commented on vhd/packer/configure-windows-vhd.ps1
> +            "https://kubernetesartifacts.azureedge.net/azure-cni/v1.4.9/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.4.12.zip"
```suggestion
            "https://kubernetesartifacts.azureedge.net/azure-cni/v1.4.12/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.4.12.zip"

```

2021-09-21 18:19 UTC, jsturtevant commented
/lgtm
/approve

2021-09-21 18:20 UTC, jsturtevant commented
@jackfrancis could you take a look again?

2021-09-21 18:37 UTC, merged