feat: add support for Kubernetes v1.19.15 and v1.20.11 on Azure Stack
Azure/aks-engine pull request #4671
Opened 2021-09-23 16:42 UTC by haofan-ms

**Reason for Change**:

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

2021-09-23 17:14 UTC, haofan-ms commented
Looks like I need to wait until @mboersma 's PRs for 1.19.15 and 1.20.11 support to merge and pull master again to pass the test issues, since I didn't include 1.19.15 and 1.20.11 in the AllKubernetesSupportedVersions map.

2021-09-23 18:21 UTC, jadarsie requested changes

2021-09-23 18:21 UTC, jadarsie commented on vhd/packer/configure-windows-vhd.ps1
> +            "https://kubernetesartifacts.azureedge.net/kubernetes/v1.19.10-azs/windowszip/v1.19.15-azs-1int.zip",
bad URIs

2021-09-23 20:20 UTC, jadarsie submitted a review, later dismissed

2021-09-25 13:55 UTC, mboersma approved these changes
/lgtm

Thanks for your patience @haofan-ms!

2021-09-25 19:08 UTC, jackfrancis approved these changes
/lgtm

2021-09-25 19:08 UTC, merged